### ISSUE TITLE
multiple router tags on one page

### ISSUE THREAD

**Issue by eddyLazar** [crisward/riot-routehandler#8] opened 2016-07-21 12:33 UTC
Are there ways to implement multiple router tags on one page?

So that something like this

**html**

``` html
<routehandler id="router1"></routehandler>
<hr>
<hr>
<routehandler id="router2"></routehandler>
```

**js**

``` js
riot.mount('#router2',{routes:routes,routeroptions:{hashbang:true}})
riot.mount('#router1',{routes:routes,routeroptions:{hashbang:true}})
```

Would produce two different tags. Now it only renders last one. I suppose it would be more closer to riot tag behavior.

**Comment by crisward** [comment] 2016-07-21 12:35
No, this is not possible. They can be nested, but not put alongside each other.

You could have a wrapping tag, which passes the params down to the tags below. This is what I've typically done.

**Comment by crisward** [comment] 2016-07-21 14:25
Out of interest, what is the use case for this?

**Comment by eddyLazar** [comment] 2016-07-26 07:19
For example, to have different blocks on one page which could handle different routes. I think it could be useful.

**Comment by crisward** [comment] 2016-07-26 19:36
OK, will leave this open and look at the issues with two route-handlers working along side each other.

**Comment by crisward** [comment] 2017-04-01 21:41
I'll be honest, I don't really need this feature personally, and I've not really had time to look into it. I'd happy accept a pull request, but since the issue is quite old now I think I'll close it. 

Thanks again for the suggestion.

**Closed as completed by crisward** 2017-04-01 21:41 UTC
Labels: enhancement, question
